language: generic

env:
  - THEOS=theos

before_script:
  - git clone --recursive https://github.com/theos/theos.git
  - ./travis/before

script:
 - make test

sudo: false

compiler:
  - clang

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
