language: generic

os:
  - linux
  - osx

sudo: false

osx_image: xcode7.2

dist: trusty

compiler:
  - clang

env:
  - THEOS=theos

before_script:
  - git clone --recursive https://github.com/theos/theos.git
  - ./travis/before

script:
 - make test
