os:
  - linux
  - osx

dist: trusty
sudo: required
osx_image: xcode7.3.1

env:
  global:
    - THEOS=theos
  
  matrix:
    #Popular libraries (http://iphonedevwiki.net/index.php/Open_Source_Projects#Developer_libraries)
    - TEST_REPO=DHowett/preferenceloader
    - TEST_REPO=rpetrich/RocketBootstrap
    - TEST_REPO=a3tweaks/Flipswitch
    - TEST_REPO=rpetrich/AppList
    - TEST_REPO=Xuzz/WeeLoader
    - TEST_REPO=Xuzz/IconSupport

before_script:
  - git clone --recursive https://github.com/theos/theos.git
  - ./travis/before

script:
 - ./travis/script

compiler:
  - clang
