language: generic

env:
 - THEOS=theos

before_script:
 - git clone --recursive https://github.com/theos/theos.git

script:
 - make

sudo: false

os:
  - linux
  - osx

compiler:
  - clang

osx_image: xcode7.2

before_script:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install dpkg ldid
