#!/bin/bash

main() {
	#argc=$#
	#argv=($@)
	#for (( i = 0; i < $argc; i++ )); do
		#echo "argv[$i] = ${argv[$i]}"
	#done

	echo "Doing 'make'"
	make
	echo "Doing 'make test'"
	make test
	echo "Doing 'make package'"
	make package
}

main $0 $@
